apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/atom-be
  name: atom-be
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|atom-be'
