apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/atom-o
  name: atom-o
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|atom-o'
