apiVersion: fn.kpt.dev/v1alpha1
kind: treactor/CreateAtoms
metadata: # kpt-merge: /create-atoms
  name: create-atoms
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|treactor/CreateAtoms|default|create-atoms'
imaxBond: 1
maxNumber: 8
treactorGo:
  imageTag: "0.1.3"
treactorJava:
  imageTag: "0.1.2"
treactorNode:
  imageTag: "0.1.7"
groups:
- group: 1
  framework: "treactorJava"
- group: 2
  framework: "treactorJava"
- group: 17
  framework: "treactorNode"
- group: 18
  framework: "treactorNode"
