# Generate by gcr.io/treactor/kpt-fn/create-atoms
apiVersion: v1
kind: Service
metadata: # kpt-merge: foo/atom-o
  labels:
    app: atom-o
  name: atom-o
  namespace: foo
  annotations:
    config.kubernetes.io/managed-by: fn:gen:gcr.io/treactor/kpt-fn/create-atoms
    internal.kpt.dev/upstream-identifier: '|Service|foo|atom-o'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 30000
    appProtocol: http
  selector:
    app: atom-o
