apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: foo/envoy
  name: envoy
  namespace: foo
  annotations:
    config.kubernetes.io/managed-by: fn:gen:gcr.io/treactor/kpt-fn/ensure-sa
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|foo|envoy'
