# Generate by gcr.io/treactor/kpt-fn/create-atoms
apiVersion: v1
kind: Service
metadata: # kpt-merge: foo/bond-n
  labels:
    app: bond-n
  name: bond-n
  namespace: foo
  annotations:
    config.kubernetes.io/managed-by: fn:gen:gcr.io/treactor/kpt-fn/create-atoms
    internal.kpt.dev/upstream-identifier: '|Service|foo|bond-n'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 30000
    appProtocol: http
  selector:
    app: bond-n
