apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: treactor/treactor-ui
  name: treactor-ui
  namespace: treactor
  annotations:
    config.kubernetes.io/managed-by: fn:gen:gcr.io/treactor/kpt-fn/ensure-sa
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|treactor|treactor-ui'
