apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: # kpt-merge: example/default
  name: default
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|Role|example|default'
rules: []
