# Generate by gcr.io/treactor/kpt-fn/gateway-api
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: # kpt-merge: treactor/treactor
  name: treactor
  annotations:
    config.kubernetes.io/managed-by: fn:gen:gcr.io/treactor/kpt-fn/gateway-api
    internal.kpt.dev/upstream-identifier: 'networking.k8s.io|Ingress|treactor|treactor'
  namespace: treactor
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: treactor-ui
            port:
              number: 80
        path: /index.html
        pathType: Exact
      - backend:
          service:
            name: treactor-ui
            port:
              number: 80
        path: /robot.txt
        pathType: Exact
      - backend:
          service:
            name: treactor-ui
            port:
              number: 80
        path: /
        pathType: Exact
      - backend:
          service:
            name: bond-1
            port:
              number: 80
        path: /treact/nodes/201/info
        pathType: Prefix
      - backend:
          service:
            name: bond-n
            port:
              number: 80
        path: /treact/nodes/299/info
        pathType: Prefix
      - backend:
          service:
            name: treactor-ui
            port:
              number: 80
        path: /treact/nodes/500/info
        pathType: Prefix
      - backend:
          service:
            name: treactor-api
            port:
              number: 80
        path: /treact/nodes/501/info
        pathType: Prefix
      - backend:
          service:
            name: atom-h
            port:
              number: 80
        path: /treact/nodes/1/info
        pathType: Prefix
      - backend:
          service:
            name: atom-he
            port:
              number: 80
        path: /treact/nodes/2/info
        pathType: Prefix
      - backend:
          service:
            name: atom-li
            port:
              number: 80
        path: /treact/nodes/3/info
        pathType: Prefix
      - backend:
          service:
            name: treactor-ui
            port:
              number: 80
        path: /treact/reactions
        pathType: Prefix
      - backend:
          service:
            name: treactor-api
            port:
              number: 80
        path: /treact/info
        pathType: Prefix
      - backend:
          service:
            name: treactor-ui
            port:
              number: 80
        path: /static
        pathType: Prefix
