apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/atom-c
  name: atom-c
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|atom-c'
