# Generate by dfdf gcr.io/treactor/kpt-fn/create-atoms
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atom-ui
  namespace: default
  annotations:
    config.kubernetes.io/managed-by: kpt:fn:gen:gcr.io/treactor/kpt-fn/create-atoms
spec:
  template:
    spec:
      containers:
      - name: atom
        image: treactor/treactor
        env:
        - name: PORT
          value: "3330"
        - name: SERVICE_VERSION
          value: 0.0.0
        - name: TREACTOR_MODE
          value: cluster
        - name: TREACTOR_TRACE_PROPAGATION
          value: w3c
        - name: TREACTOR_TRACE_INTERNAL
          value: "1"
        - name: TREACTOR_RANDOM
          value: nothing_secret
        - name: SERVICE_NAME
          value: atom-ui
        - name: TREACTOR_NUMBER
          value: 500
        - name: TREACTOR_MAX_NUMBER
          value: 8
        - name: TREACTOR_MAX_BOND
          value: 0
        - name: TREACTOR_COMPONENT
          value: ui
        - name: TREACTOR_MODULE
          value: treactor
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(HOST_IP):4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        ports:
        - containerPort: 3330
          name: http
          protocol: TCP
    metadata:
      labels:
        app: atom-ui
  selector:
    matchLabels:
      app: atom-ui
  serviceAccountName: atom-ui
